name: Playwright Tests

permissions:
  contents: write
  actions: write
  id-token: write
  pages: write

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0,8,16 * * *'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
        MONGO_COLL_NAME: ${{ secrets.MONGO_COLL_NAME }}
      run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=blob
      
    - name: Upload blob report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: all-blob-reports-${{ matrix.shardIndex }}
        path: blob-report
        retention-days: 1

  report:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Download blob reports
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: all-blob-reports-*
          merge-multiple: true
          
      - name: Merge HTML and JSON Reports
        env:
          PLAYWRIGHT_JSON_OUTPUT_NAME: results.json
        run: npx playwright merge-reports --reporter=html,json ./all-blob-reports

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        id: deployment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_SERVER: ${{ github.server_url }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_RUN: ${{ github.run_id }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref_name }}
          GITHUB_EVENT: ${{ github.event_name }}
          TEST_RESULT: ${{ needs.test.result }}
          REPORT_URL: ${{ steps.deployment.outputs.page_url }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: node slack-notify.js
